# Generated by Django 4.1.7 on 2023-02-22 21:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('productID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=500)),
                ('productImg', models.ImageField(upload_to='accounts/images')),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ProfileDetails',
            fields=[
                ('profileDetailsID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('phone', models.BigIntegerField(unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('profileCategory', models.CharField(choices=[('EndCustomer', 'EndCustomer'), ('ManufacturePanel', 'ManufacturePanel'), ('WholesalePanel', 'WholesalePanel'), ('RetailerPanel', 'RetailerPanel')], max_length=20)),
            ],
        ),
    ]
